### DISCUSSION TITLE
intermediate review / refactoring

### DISCUSSION THREAD

**Discussion by carstenschelp-surf** [SLURM-CLI-API-Proxy/SLURM-CLI-API-Proxy-client#38] [General]
Hi @hcadavid, I changed the squeue output formatting to be more flexible.
Could you review the changes I made in the "format_strings" branch?
I don't feel comfortable with that many static methods and static class variables.
Also, I think I could put more of the formatting knowledge into the get-jobs response class - or maybe into an extra formatting class altogether. What do you think?

**Comment by carstenschelp-surf** [comment]
I already have some test code ready that I will transfer to the branch, shortly.

**Comment by carstenschelp-surf** [comment]
While adding test code, I realize that I don't have to put all methods in that module inside the class.
Relaxes the code a little, already.

**Comment by hcadavid** [comment]
Hi @carstenschelp-surf, just a couple of comments on what I understand from your changes. I see that you are including a new YAML file, but the way you are accessing it (using a relative path) may cause problems when using the packaged version of the tool. 

https://github.com/SLURM-CLI-API-Proxy/SLURM-CLI-API-Proxy-client/blob/6beb84773a08b04c604d435cbac62ca10ce5a309/src/slurm_api_cli_proxy/client_args_linker/v39/slurm_api_client_wrapper_v39.py#L43-L47

I haven't checked in detail, but I also see that this YAML file makes reference to methods within this low-level module. The YAML files defined in the tool are used for dynamically enabling arguments on the tool, and these expected to be decoupled from the implementation details of such modules (as this may eventually cause errors difficult to track in the future, if, for example, one of the referred methods is removed or renamed). Given that your YAML serves a different purpose, I think it would be more convenient (also to prevent file-access problems) to just use a dictionary defined on a new Python module instead, within the v39 package (`v39/squeue_format_types_dictionary.py` or something like that), e.g.:

From this:

````
# Format "types" for squeue -o...
# Please refer to https://slurm.schedmd.com/squeue.html

A:
  descr: Job id. Here, synonymous with %i. 
  head: JOBID
  json_path: job_id
D:
  descr: Number of nodes allocated to the job or the minimum number of nodes required by a pending job.
  head: NODES
  method: get_D_format_value
...
````


To this:


````
format_types = {
    "A": {
        "descr": "Job id. Here, synonymous with %i.",
        "head": "JOBID",
        "json_path": "job_id",
    },
    "D": {
        "descr": "Number of nodes allocated to the job or the minimum number of nodes required by a pending job.",
        "head": "NODES",
        "method": "get_D_format_value",
    },
    ...
}
````


In any case, feel free to create a PR when you have your implementation working. We can keep discussing and make changes within it before doing the merge.
